### ISSUE TITLE
Web Config has changed vs the instructions and now very confusing

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/Research-Project-Code-Sample#2]
The Web Config contains the following feilds to be filled out

```
    <add key="ida:SiteURL" value="[[ FILL IN ]]" />
    <add key="ProjectsListName" value="Research Projects" />
    <add key="ReferencesListName" value="Research References" />

    <!-- Authentication configuration -->
    <add key="ida:Resource" value="[[ FILL IN ]]" />
    <add key="ida:ClientId" value="[[ FILL IN ]]" />
    <add key="ida:AppKey" value="[[ FILL IN ]]" />
```

But the instructions actually contain this;

Setting Example
ASP.NET Web Application https://localhost:44362
Office 365 Tenant ID    contoso
Office 365 Tenant ID URL    contoso.onmicrosoft.com
Azure AD App Name   ContosoResearchTracker
Azure AD App ID URL Name    https://contoso.onmicrosoft.com/ContosoResearchTracker
Azure AD App Client ID  C78b2619-86a7-4c27-c99a-e0e34dcbf341
Azure AD App Key    VnXElqNkFP+Cl1mo0KWOytae8NxzKmrgFOObTz2YpEE=
Fully Qualified SharePoint Online Resource  https://contoso.sharepoint.com
Fully Qualified URL of the SharePoint Site  https://contoso.sharepoint.com/sites/ContosoResearchTracker/

So it is assumed the SITEURL is the fully qualified URL of the sharepoint site, thats fine

But what is ida:Resource?  Is this the Tenant ID? or the SP Online Resource? ie https://contoso.sharepoint.com?

This needs to be updated.

**Comment by deadalusai** [comment]
Hi Nigel.

Please check out the [last few instructions in the README](https://github.com/OfficeDev/Research-Project-Code-Sample/blob/361f7c509b67c66dbe2765a7223d86caf2fad890/src/SpResearchTracker/README.md#line-21--app-setting-idasiteurl). 

They instruct on exactly which settings from the table at the top of the README to use in the Web.config file.

The other READMEs for WordResearchTracker and OutlookResearchTracker follow the same pattern.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
