### ISSUE TITLE
Can not get into the Project for the Android App

### ISSUE THREAD

**Issue by guhasayantan** [OfficeDev/Research-Project-Code-Sample#3]
I did the initial setup as instructed 
https://github.com/OfficeDev/Research-Project-Code-Sample/tree/master/mobile/ResearchTracker.Android

I could set the list of items from the App. but could not get into each item of the project.

Error

"The query to field 'Project' is not valid. The $select query string must specify the target fields and the $expand query string must contains Project."

Please let me know
![image](https://cloud.githubusercontent.com/assets/12722063/9152479/57bf3fc8-3ddf-11e5-96ca-3c441ea4a5a1.png)

**Comment by deadalusai** [comment]
The lines which control the `$select` and `$expand` parameters in that query are [here](https://github.com/OfficeDev/Research-Project-Code-Sample/blob/361f7c509b67c66dbe2765a7223d86caf2fad890/mobile/ResearchTracker.Android/src/ResearchTracker/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java#L10-L14).

The function which builds and executes the actual query is [here](https://github.com/OfficeDev/Research-Project-Code-Sample/blob/361f7c509b67c66dbe2765a7223d86caf2fad890/mobile/ResearchTracker.Android/src/ResearchTracker/app/src/main/java/com/microsoft/researchtracker/sharepoint/data/ResearchDataSource.java#L53-L67). You can see the static `SELECT` and `EXPAND` fields from the first link being passed through here.

The query filters for *Project References* with a `Project` field equal to the given `ProjectId`.

The error message is odd, but may suggest that the two SharePoint Lists do not have the expected fields. Please note that this Android project makes no attempt to create the SharePoint lists if they do not already exist - you will need to either build the two Lists manually or deploy and run the [SpResearchTracker](https://github.com/OfficeDev/Research-Project-Code-Sample/tree/361f7c509b67c66dbe2765a7223d86caf2fad890/src/SpResearchTracker) first.

The code in *SpResearchTracker* which bootstraps the two lists is [here](https://github.com/OfficeDev/Research-Project-Code-Sample/blob/361f7c509b67c66dbe2765a7223d86caf2fad890/src/SpResearchTracker/Controllers/ConfigurationsController.cs#L40-L59).

**Comment by jthake** [comment]
You make a great point here. this is really a companion app to the core research tracker web application. We should probably catch that the lists aren't there and note that issue. I don't have the Android skills myself to do this. It would make a  great pull request if you had the time to catch the error and present a more friendly message?

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
